코드 최신화 및 검색 기능 디버깅
Team-PATCH/Harmony-iOS pull request #127
Opened 2024-10-18 17:49 UTC by sion555

## 💡 Issue Number
- #126 

## 🤷‍♂️ Description
- 코드를 최신화했습니다.(새로운 추억 오버레이 및 추억카드 목록 최상단 노출 기능 추가)
- 검색 기능 미작동 현상 디버깅 완료

2024-10-19 12:27 UTC, WaterBean commented on Harmony/Harmony/Views/MemoryCard/MemoryCardsView.swift
> +    @EnvironmentObject var viewModel: MemoryCardViewModel
'@EnvironmentObject'로 변경된 이유가 있을까요? 이러면 위에서 뿌려주는 친구가 있어야할 것 같은데... 다시 한번 확인 부탁드립니다!

2024-10-19 12:37 UTC, WaterBean requested changes
9번과 12번 줄에 코멘트 남겨놓았습니다!

2024-10-19 12:37 UTC, WaterBean commented on Harmony/Harmony/Views/MemoryCard/MemoryCardsView.swift
> +import Kingfisher
KingFisher가 쓰이는 부분이 없어보여 수정이 필요해보입니다

2024-10-20 08:02 UTC, sion555 commented on Harmony/Harmony/Views/MemoryCard/MemoryCardsView.swift
> +    @EnvironmentObject var viewModel: MemoryCardViewModel
"새로운 추억" 오버레이가 추억카드 목록(MemoryCardsView)에서 표시되지 않는 문제를 해당 변경사항으로 해결했었습니다.
상위 레벨인 HarmonyApp.swift에서 StateObject로 뿌려주고 있는 것을 확인하실 수 있습니다.

한 줄 요약:
StateObject일 경우, MemoryCardsView에서 최신 추억카드에 "새로운 추억" 오버레이가 표시되지 않습니다.

2024-10-20 08:03 UTC, sion555 commented on Harmony/Harmony/Views/MemoryCard/MemoryCardsView.swift
> +import Kingfisher
확인했습니다. 수정사항 반영하겠습니다.

2024-10-20 08:04 UTC, WaterBean commented on Harmony/Harmony/Views/MemoryCard/MemoryCardsView.swift
> +    @EnvironmentObject var viewModel: MemoryCardViewModel
아하,..그러면 기존에 StateObject였던게 잘못되었던 것이군요 알겠습니다!!

2024-10-20 08:08 UTC, WaterBean approved these changes

2024-10-20 08:08 UTC, WaterBean commented on Harmony/Harmony/Views/MemoryCard/MemoryCardsView.swift
> +    @EnvironmentObject var viewModel: MemoryCardViewModel
확인했습니다! 머지하고, 앱 통합 바로 들어가볼게요 ㅎㅎ

2024-10-20 08:10 UTC, thisisdana49 approved these changes
LGTM! 확인했으니까 머지 하겠습니다~ :)

2024-10-20 08:10 UTC, merged