[Feat] LoginView에서 SimpleOnboardingView로 이동할 수 있는 버튼과 관련 기능 추가 및 디버깅
Team-PATCH/Harmony-iOS pull request #134
Opened 2024-11-20 15:25 UTC by sion555

## 💡 Issue Number
- #133 

## 🤷‍♂️ Description
- 뷰 우측 상단에 SimpleOnboardingView로 이동할 수 있는 버튼 추가.
- 계정 혹은 권한으로 앱에 진입할 수 없는 문제 등 디버깅.

## ✳️ Remarks
- LoginView에서 필요하지 않은 의존성인 import KakaoSDKUser를 제거했습니다.(authViewModel.loginWithKakao() 메서드는 AuthViewModel에서 처리됨)
- ContentView에서는 SimpleOnboardingView로의 이동 기능 추가와 네비게이션 상태 관리의 일관성을 위해 NavigationStack과 Group으로 분기 처리 구문 전체를 감싸는 방식으로 수정하였고 기존 코드의 기능은 모두 정상적으로 유지됩니다.
- 버튼을 .mainGreen 색상의 귀여운 하트 모양으로 만들었습니다😆👍

2024-11-21 07:47 UTC, WaterBean commented on Harmony/Harmony/ContentView.swift
## EnvironmentObject 주입 위치 관련
- 어제 회의 때 잠깐 말씀드렸듯이 EnvironmentObject는 @StateObject로 생성한 인스턴스를 .environmentObject를 통해 최상위 뷰에 한번만 주입시켜주면 주입한 하위 뷰 어디에서나(중간 계층에 있는 뷰이던, 최하위에 있던) 받아서 사용할 수 있습니다!! 즉 중간 뷰에서 계속 연결연결 시켜줄 필요 없다는 얘기입니다 ㅎㅎ
참고 링크) https://green1229.tistory.com/229

14번 라인에 @environmentObject 지워주시고, 전역으로 뿌려줘야 하는 부분은 MainTabView 내부에서 뿌려주면 되지 않을까 싶어요!
- @EnvironmentObject를 MainTabView 내부에 해당 뷰모델을 사용하는 홈뷰, 그리고 메모리카드뷰에만 넣어주세요.

2024-11-21 10:40 UTC, WaterBean requested changes
전반적인 로직 변경이 필요해보입니다!

2024-11-21 10:40 UTC, WaterBean commented on Harmony/Harmony/ContentView.swift
## NavigationStack이 두번 감싸져 있는 부분 관련
작성해주신 코드는 현재 어떤 구조냐면,
```Swift
NavigationStack { // 첫번째 NavigationStack
    MainTabView {
        HomeView {
            NavigationStack { // 첫번째 NavigationStack
            
            }
        }
    }
}
```
NavigationStack이 두번 감싸져 있게 되면 네비게이션에 쌓이는 상태가 정상적으로 동작하지 않을 가능성이 매우 높습니다.
그리고 홈뷰 말고도, MainTabView하위뷰에서 NavigationStack을 사용하는 뷰가 대부분인데, 다른 탭에도 분명 영향이 있을거고...아무튼 이렇게 전체 래핑을 해서 toolbar를 통해 심플온보딩뷰를 추가하는.. 그것도 온보딩뷰모델을 통해 추가하는 것이 앱 전체 동작에 아주 큰 영향을 주고 있어요.. 

일단 온보딩용 NavigationStack 자체를 사실상 앱 전체로 감싸는 것보다는 다른 방법을 강구하는 게 좋아보여요.

2024-11-21 10:40 UTC, WaterBean commented on Harmony/Harmony/ContentView.swift
> -            LoginView()
제 생각에는, 로그인 뷰 내부에 심플온보딩의 기능을 하는(심플온보딩뷰 자체가 아니라) 버튼을 임시로 넣어야 해요. 말씀드렸던 매크로 문법으로 개발 환경과 프로덕션 환경을 분리해서요.

2024-11-21 10:40 UTC, WaterBean commented on Harmony/Harmony/ViewModels/AuthViewModel.swift
흠... 이건 왜 이렇게 변경되어야만 했을까요? simpleonboardingview자체를 사용안할 것 같아 변경 자체를 안해도 괜찮을 것 같아요!

**그리고, 코드 변경시 주석을 가급적 사용 안했으면 합니다....**

2024-11-21 10:40 UTC, WaterBean commented on Harmony/Harmony/Views/Auth/LoginView.swift
- KakaoSDKUser를 없앤 건 좋아보입니다.
- LoginView에 authVM과 onboardingVM을 env object로 같이 주입해주고, 간편 로그인 시 둘의 프로퍼티를 각각 바꿔주는 게 좋아보이네요!
- 다만, onboardingVM이 개발 환경에서만 주입되어야 할 것 같습니다.
- 뷰에는 'VIP로 로그인' 그리고 'Member로 로그인' 버튼이 들어가야할 텐데, 이것들도 개발환경에서만 보여야 됩니다!

2024-11-21 10:40 UTC, WaterBean commented on Harmony/Harmony/Views/Onboarding/SimpleOnboardingView.swift
onboardingview는 사용하지 않습니다..!!! 
- 버튼에 있는 로직만 살려서 LoginView에서 사용합니다! 
- 로그아웃 로직도 응용해서 만들어보시면 좋을 것 같아요 :)

2024-11-26 14:35 UTC, sion555 commented on Harmony/Harmony/ContentView.swift
14번 라인의 EnvironmentObject 지우고, MemoryCardViewModel을 사용하는 뷰에만 주입했습니다!

2024-11-26 14:36 UTC, sion555 commented on Harmony/Harmony/ContentView.swift
> -            LoginView()
조건부 컴파일을 사용하는 코드로 변경하고, SimpleOnboardingView를 사용하는 방식이 아닌 LoginView에 버튼을 추가하는 방식으로 변경했습니다!

2024-11-26 14:38 UTC, sion555 commented on Harmony/Harmony/ViewModels/AuthViewModel.swift
주석 제거하고, 원래대로 되돌렸습니다!

2024-11-26 14:43 UTC, sion555 commented on Harmony/Harmony/Views/Auth/LoginView.swift
네, envObject로 주입하고 간편 로그인의 요구사항에 맞게 프로퍼티를 변경하는 방식을 사용하였고, 개발환경에서만 보이게 작성했습니다!

2024-11-26 14:43 UTC, sion555 commented on Harmony/Harmony/Views/Onboarding/SimpleOnboardingView.swift
로직을 전부 수정하여 SimpleOnboardingView를 사용하지 않게 변경하였습니다. 로그아웃 로직도 구현 완료했습니다!

2024-11-27 06:06 UTC, WaterBean requested changes
오늘 회의 때 같이 플로우 점검해봐요..!!

2024-11-27 06:06 UTC, WaterBean commented on Harmony/Harmony/Views/Auth/LoginView+Debug.swift
좋아보입니다! 별도로 파일로 분리한 것도 괜찮은 것 같구요!

2024-11-27 06:06 UTC, WaterBean commented on Harmony/Harmony/Views/Home/HomeView.swift
어제 설명해주신 크래시가 나는 부분이 이 부분이 아닐까 싶은데요!
이전에 짰었던 로직은 로그인/온보딩 여부를 각각 확인해 둘 다 끝났다면 홈뷰로 전환되는 로직이었어요. 이 부분을 ContentView에서 담당했구요.(if-elseif문을 통해서) 
로그아웃이나 온보딩 둘중에 하나라도 안되어있으면 홈뷰가 아니라 온보딩뷰 시작점..혹은 로그아웃뷰로 넘어가구요. 그래서 logout 메서드로 접근해서, AuthViewModel의 isLoggedIn의 값을 변경해주면 자동으로 바뀌게 되구요! (사실.. 로그인 이후 서버 토큰을 사용하기 때문에 이 여부를 검사하는 로직으로 궁극적으로 변경되어야 할 것 같다고 생각이 드네요 ㅠ..오늘 회의 때 다이어 그램을 만드는 것이 좋아보여요)

여기서는 onboardingViewModel의 네비게이션을 다루는 부분을 Navigation path를 제거하면서 화면을 전환하는 것이 아니라,(그리고 여기는.... 온보딩 하는 시점이 아닌데, NavigationStack으로 감싸져있는게 잘못되었다고 생각합니다.)
logout 메서드로 로그인 상태만 변경해주는 로직만 있어도 화면은 잘 전환될 것이니,(상태가 변경되니 뷰도 다시 그려짐) logout()만 남기고, ContentView의 변경사항은 PR 올리기 이전 시점으로 되돌리면 잘 작동될 것으로 생각되네요!

2024-11-27 06:06 UTC, WaterBean commented on Harmony/Harmony/Views/Auth/LoginView.swift
LoginView에서 memoryCardView는 사용되지 않을 것 같아서 이 부분도 수정되면 좋을 것 같아요!

2024-11-27 06:06 UTC, WaterBean commented on Harmony/Harmony/Views/Home/HomeView.swift
> +                            authViewModel.logout()
이부분만 남기면 좋을 것 같아요! person.circle 친구도 일단 되살리면.. 좋을 것 같아요ㅎㅎ

2024-11-27 06:06 UTC, WaterBean commented on Harmony/Harmony/ContentView.swift
>          NavigationStack(path: $onboardingViewModel.navigationPath) {
HomeView에 남긴 코멘트 읽어주시면 감사하겠습니다!!

2024-12-04 13:43 UTC, WaterBean approved these changes

2024-12-04 13:44 UTC, thisisdana49 approved these changes

2024-12-04 13:44 UTC, thisisdana49 commented on Harmony/Harmony/ViewModels/AuthViewModel.swift
주석 처리 된 생성자는 남겨놓으신 이유가 있나요? 필요하지 않다면 주석 말고 그냥 지우는 것이 더 좋아보입니다!

2024-12-05 08:59 UTC, merged